{% set version = "0.16.0" %}

package:
  name: ua-parser
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/ua-parser/ua-parser-{{ version }}.tar.gz
  sha256: ace314a7c04f89d37282d5c837d1189960314a336270b41f6d6171097c8dfe9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pyyaml >=5.4.0,<=5.5
  run:
    - python >=3.6

test:
  imports:
    - ua_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache-2.0
  license_file: ua_parser/LICENSE
  license_family: Apache
  summary: Python port of Browserscope's user agent parser
  dev_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
