{%set name = "ua-parser" %}
{%set version = "0.8.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "97bbcfc9321a3151d96bb5d62e54270247b0e3be0590a6f2ff12329851718dcb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python

test:
  imports:
    - ua_parser

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache 2.0
  license_family: Apache
  summary: "Python port of Browserscope's user agent parser"
  dev_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
