{% set version = "0.10.0" %}

package:
  name: ua-parser
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/ua-parser/ua-parser-{{ version }}.tar.gz
  sha256: 47b1782ed130d890018d983fac37c2a80799d9e0b9c532e734c67cf70f185033

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
    - pyyaml
  run:
    - python

test:
  imports:
    - ua_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache-2.0
  license_file: ua_parser/LICENSE
  license_family: Apache
  summary: "Python port of Browserscope's user agent parser"
  dev_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
