{% set name = 'ua-parser' %}
{% set version = "0.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db51f1b59bfaa82ed9e2a1d99a54d3e4153dddf99ac1435d51828165422e624e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - pyyaml
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - ua_parser
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache-2.0
  license_file: ua_parser/LICENSE
  license_family: Apache
  summary: A python implementation of the UA Parser
  description: |
    A python implementation of the UA Parser.
  dev_url: https://github.com/ua-parser/uap-python
  doc_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
