# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Jfu9lzSxlGCLrQPjsV6OS/DE1Y4usXVgMPVSxGp0tc0N0JG6r+0CxMj8bejlfWGEdApgQ8BD2+jfKNxjmkHqHYGLZPBIrSbaZ4YH9Y1wgjuE1X3wafk4fDrEKD3BU+bRsuWypkqhanYQWTVdnsB9lFBH6XRQf+uZgxPQl1cEMj3/fEx2wiBBvzBjcTVjZgFgto1Gyj73TtoNFhoBdirL0TxnSk5YxlYOE58N0yC0jum9PYxOgJWupOrvzICjpwIFAgznThRalMNRUig5hLwMOCYGaAZw3Gy4FzNCCcvWPV8V8jG0DO/ZEg9+hNIlTao9dJuza7HF+mhsSofJNzJJDqwLy4bQuwa38bjG/9v+hH6g7CQh5eneT1Vp/qw67dZ+uHwTf09hdSqcUZqGl6MN9cZzHFFyJmUN5zsIJZBOO9/BpDMXlQsrhDFKKiaLQrVAedOnnRL0MgO+/xwekaVbD6vjucmv4hRW83Tyz7NQ3fpYqldll8iPJk/55gpY7euLFkcdaBMaiH6MGQrnGt+akbG0/Wc2mpRM7GpziTYZJ7cyZJeWiBm0QVLeErsSvWY153VOKv3E7eX+xLJ8o/42rCefq1TWoG9eR/X+oYvfDAty6pFKVrn2kJEt1ppr879WLTmh7CxcVo/biohx8s7+5nQN5gyvIeaqHF+7AcLDGVs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
