travis:
  secure:
    BINSTAR_TOKEN: Jfu9lzSxlGCLrQPjsV6OS/DE1Y4usXVgMPVSxGp0tc0N0JG6r+0CxMj8bejlfWGEdApgQ8BD2+jfKNxjmkHqHYGLZPBIrSbaZ4YH9Y1wgjuE1X3wafk4fDrEKD3BU+bRsuWypkqhanYQWTVdnsB9lFBH6XRQf+uZgxPQl1cEMj3/fEx2wiBBvzBjcTVjZgFgto1Gyj73TtoNFhoBdirL0TxnSk5YxlYOE58N0yC0jum9PYxOgJWupOrvzICjpwIFAgznThRalMNRUig5hLwMOCYGaAZw3Gy4FzNCCcvWPV8V8jG0DO/ZEg9+hNIlTao9dJuza7HF+mhsSofJNzJJDqwLy4bQuwa38bjG/9v+hH6g7CQh5eneT1Vp/qw67dZ+uHwTf09hdSqcUZqGl6MN9cZzHFFyJmUN5zsIJZBOO9/BpDMXlQsrhDFKKiaLQrVAedOnnRL0MgO+/xwekaVbD6vjucmv4hRW83Tyz7NQ3fpYqldll8iPJk/55gpY7euLFkcdaBMaiH6MGQrnGt+akbG0/Wc2mpRM7GpziTYZJ7cyZJeWiBm0QVLeErsSvWY153VOKv3E7eX+xLJ8o/42rCefq1TWoG9eR/X+oYvfDAty6pFKVrn2kJEt1ppr879WLTmh7CxcVo/biohx8s7+5nQN5gyvIeaqHF+7AcLDGVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
