travis:
  secure:
    BINSTAR_TOKEN: r5V6JO+kLl3xNMISrjg5P63FLH4ON6GHioEnQxlMgpl2Fm3RiTmHI00acbZZ6IuaSVf6/p+j9UEYeLV6PI5Sob/e3684fwl0c9TpM7xDToZAvsVeYSyoJvWF5WthMPRJeBo3VeyBorO/s7SlS+Xx0syivFGdl5XaImZfqeAM9rBM1gSEl6fqXjYBgHdhIqXMhKYldiBN2nENnhqkzMqjCoY1KAt4g61YpYwdboXF1/buI8j1h9CcakZQgD1L7mc1VADs6tqYHT35FabCNvkdCdrISuZH3zHHH1RSzpS+/yNufy3Y1M+1ZbFsCbb5OgaSkNZrSPNXuvWw+lcqPM2O5DPWytXZEccn38bCP/HT6ggGIqtCLPSC6qNlc4St/bhTZtjtd5uR9h+3gyYLXBoNKV87ECbttJwpoqq+r4DdHxODeb5SQIaqVNvu4LzUnZR50FfmGaLGByX4WFmAF795mDoXVsZL0X/FUGMTkXO9h24NCiA5ZSpPQRI6M83BaIUr0nVcQuBVWEk+ZIYMSd49FJ4hxS6WzN7KUTn8H3y2dL9Kk7B4YxXodS5F/HBEsc3yfnENsTOhcJ8t/lR1Y2C0+tSfTvXdpHDmLBJeJE56N004P5vHWtFPWBSp5MfnDlFXDPvvKhxCxdvjvfIXB2bv5MnSt3dwlCLFlHIS9E7LL3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
