travis:
  secure:
    BINSTAR_TOKEN: DbMcf8YdMjYt263II298LulzSXQyzEVxNpobpdN4fHgf0XZQ2M/DtQyVXD732NcOQyeh1q2+mYh+KjanAp8mrjXnXE66mSX6qn1eJXdX/JhA+9L51iSGHgDvzP9x9AB0YrqZVRp6Re9wPlmH3YlrVokQQc9Zjt6A3YuvUCFS4CB2AliwGeHUqyKuTnbNABqMoNrDMNkKwoFU33Yy6b7hbl+iT/p9s7jexWbnnA1hwdJCIMcMSElPaymwUrrIUb0KlpnVnWjwWZBmwifWmmha+Yp8uGRxQ+8eQ7RjMGjgt6CwqWBu/0CytGUO9mUrBRoMKTm4bfkH8k2878MK24YhZ5J2rXfktYramFB8gj7V2AJbksUPShFR2LCGWwy2QLUdOLky0+f8TNG8D/nhD5FC745yVYjZyDpHc+yUttmUWshhl2qjOJ2PbztMoFLknt+EeFEtJogtqNo/Bs3UidOwsSay+UVcfIPCfTKRgajKsKaLppiHh7qnv7zqmUhYCecEPtKXM5j8tAzpLBxpfkdJX2g2vPq7KfZEyd+8a0XNRWjMIKUZKHkKqunNjWoNuggC+BVSEcfFpJIMUVHJ7/0u+aeE2EYosS+6c2H9yZ7uSqj4Qgy72qgp6JrAx9TwZa1w3Ny0PT7CzTNf1ERYi6y8TzSZMszxoIfzwmrSeeXnVtk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
